apiVersion: v1
kind: Secret
metadata:
  name: jwt-keys
  namespace: libeasy
type: Opaque
data:
  # Encode with: cat keys/private_key_pkcs8.pem | base64 -w 0
  private_key.pem: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLiBZT1VSIEJBU0U2NCBFT KNEVSBQR KLWQVRFIEFURVKFWS0tLS0tRU5EIFBSSUFURSBLRVKTLS0tLQo=
  # Encode with: cat keys/public_key.pem | base64 -w 0
  public_key.pem: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KLi4uIFlPVVIgQkFTRTY0IEVOQ09ERUQgUFVCTElDIEtFWQotLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0K
---
# To generate real values, run:
# kubectl create secret generic jwt-keys \
#   --from-file=private_key.pem=./keys/private_key_pkcs8.pem \
#   --from-file=public_key.pem=./keys/public_key.pem \
#   --namespace=libeasy
