apiVersion: v1
kind: ConfigMap
metadata:
  name: loan-service-config
  namespace: libeasy
data:
  SPRING_PROFILES_ACTIVE: "dev"
  DB_HOST: "loan-postgres"
  DB_PORT: "5432"
  DB_NAME: "loan_db"
  DB_USERNAME: "postgres"
  GATEWAY_URL: "http://gateway:8080"

