apiVersion: v1
kind: Service
metadata:
  name: book-service
  namespace: libeasy
spec:
  selector:
    app: book-service
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP

