apiVersion: v1
kind: Secret
metadata:
  name: auth-mysql-secret
  namespace: libeasy
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_DATABASE: auth_db
  MYSQL_USER: authuser
  MYSQL_PASSWORD: authpass
